obj-$(CONFIG_DRM_PANEL_FAIRPHONE_FP2_OTM1902B) += panel-fairphone-fp2-otm1902b.o
obj-$(CONFIG_DRM_PANEL_FAIRPHONE_FP2_S6D6FA1) += panel-fairphone-fp2-s6d6fa1.o
obj-$(CONFIG_DRM_PANEL_SONY_LEO_NOVATEK_LGD) += panel-sony-leo-novatek-lgd.o
